### ISSUE TITLE
Practica_De_Libreria_DLL_visual_Studio

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Abraham890#2]
[Abraham_Reyes_Ortiz_Reporte _De_Practica_De_Libreria_DLL_visual _4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Abraham890/files/6339913/Abraham_Reyes_Ortiz_Reporte._De_Practica_De_Libreria_DLL_visual._4US.pdf)

**Comment by Aricel117** [comment]
Excelente Trabajo Tiene 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
